Algoritmo "Questao03L1"
// Disciplina   : LABORATÓRIO DE ALGORITMO
// Professor   : LAYSA MABEL 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/03/2022
Var
// Seção de Declarações das variáveis 

   r: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Digite o raio: ")
   leia (r)
   escreva ("A area é = ", exp(r, 2) * pi)

Fimalgoritmo